[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "kepler-chessanalitic"
version = "0.1.0"
description = "Herramienta inteligente de análisis de datos para jugadores de ajedrez de la FIDE"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "pandas",
    "numpy",
    "pydantic",
    "requests",
    "tqdm",
    "loguru",
    "python-dotenv",
    "seaborn",
    "scipy",
    "matplotlib"
]

[project.optional-dependencies]
dev = [
    "pytest",
    "ipykernel"
]
db = [
    "sqlalchemy"
]
ml = [
    "scikit-learn"
]
app = [
    "streamlit>=1.35",
    "plotly>=5.20",
    "pyarrow",
]

[tool.setuptools]
package-dir = {"" = "."}

[tool.setuptools.packages.find]
where = ["."]
include = ["src*"]

[tool.pytest.ini_options]
minversion = "7.0"
addopts = "-ra -q"
testpaths = [
    "tests",
]